### ISSUE TITLE
BadParcelableException for Google Login API

### ISSUE THREAD

**Issue by DaRkRaGe** [playgameservices/android-basic-samples#207]
Google play services: 9.0.2
Support libs: 24.0.0
Android studio 2.2 Preview 4
Gradle 2.2-alpha-4

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.my.app/com.google.android.gms.auth.api.signin.internal.SignInHubActivity}: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: 佅￿l￿*https://www.googleapis.com/auth/plus.login,佅￿$￿profile(佅￿ ￿email,佅￿$￿
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
       at android.app.ActivityThread.access$900(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
       at android.os.Handler.dispatchMessage(Handler.java)
       at android.os.Looper.loop(Looper.java)
       at android.app.ActivityThread.main(ActivityThread.java)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
Caused by android.os.BadParcelableException: ClassNotFoundException when unmarshalling: 佅￿l￿*https://www.googleapis.com/auth/plus.login,佅￿$￿profile(佅￿ ￿email,佅￿$￿
       at android.os.Parcel.readException(Parcel.java)
       at android.os.Parcel.readException(Parcel.java)
       at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java)
       at android.app.Activity.startActivityForResult(Activity.java)
       at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:48)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:75)
       at android.app.Activity.startActivityForResult(Activity.java)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:871)
       at com.google.android.gms.auth.api.signin.internal.SignInHubActivity.zzj(Unknown Source)
       at com.google.android.gms.auth.api.signin.internal.SignInHubActivity.onCreate(Unknown Source)
       at android.app.Activity.performCreate(Activity.java)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
       at android.app.ActivityThread.access$900(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
       at android.os.Handler.dispatchMessage(Handler.java)
       at android.os.Looper.loop(Looper.java)
       at android.app.ActivityThread.main(ActivityThread.java)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)

**Comment by mayank250004** [comment]
Any Solution ??
i have same issue!

**Comment by ifynk** [comment]
I have too

**Comment by arisembekss** [comment]
I have too.. So how to fix it? I've been spend a ton time to find the solution but still can't found it. In my case that crash log just happen in xiaomi device

**Comment by grydstedt** [comment]
Me too. Any help?

**Comment by nsmesta** [comment]
Anybody here with the solution ?Please help

**Comment by akkishinde** [comment]
The fix for this will be out in Play services 10.4
You can see this thread, https://github.com/googlesamples/google-services/issues/240

**Comment by isaisachen** [comment]
This is a different issue than googlesamples/google-services#240.

Anyone has bug report?

**Comment by claywilkinson** [comment]
This has been fixed in the last SDK update. Please reopen this issue with a log of it happening if you encounter the problem after updating.

**Comment by ankit209** [comment]
@claywilkinson  Nope, it seems the exact same issue still persists in sdk 11.0.2 
support lib: 25.3.1
device: Xiaomi Redmi Note 3
play-services version: 11.0.2

This is how I am invoking google sign in from my fragment:
```
Intent signInIntent = Auth.GoogleSignInApi.getSignInIntent(mGoogleApiClient);
getActivity().startActivityForResult(signInIntent, REQUEST_GOOGLE_SIGN_IN);
```
And I am getting the same crash

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sharesmile.share/com.google.android.gms.auth.api.signin.internal.SignInHubActivity}: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: ,佅￿$￿openid￿H159550091621-ja0nfl97se4qeeqcc4950fdqu20b5ipj.apps.googleuserconte
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2332)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2394)
       at android.app.ActivityThread.access$800(ActivityThread.java:154)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5276)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)
Caused by android.os.BadParcelableException: ClassNotFoundException when unmarshalling: ,佅￿$￿openid￿H159550091621-ja0nfl97se4qeeqcc4950fdqu20b5ipj.apps.googleuserconte
       at android.os.Parcel.readException(Parcel.java:1548)
       at android.os.Parcel.readException(Parcel.java:1499)
       at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2441)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1500)
       at android.app.Activity.startActivityForResult(Activity.java:3796)
       at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
       at android.app.Activity.startActivityForResult(Activity.java:3757)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
       at com.google.android.gms.auth.api.signin.internal.SignInHubActivity.onCreate(Unknown Source)
       at android.app.Activity.performCreate(Activity.java:6041)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1109)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2285)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2394)
       at android.app.ActivityThread.access$800(ActivityThread.java:154)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5276)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)

**Comment by isaisachen** [comment]
While we cannot repro on Xiaomi devices with Google Play services, we did find a repro on a Xiaomi device without Google Play services. We will have a potential fix in new version of SDK this Sep / Oct.

**Comment by elsennov** [comment]
Agree with @ankit209 , still happen in play services 11.0.2.

**Comment by autonomousapps** [comment]
Can we please re-open this ticket? It's still happening. I work for Chess.com and we recently added google sign-in capabilities. We have 300k daily users and I'm seeing it at around ~9x per day. We are using **play services 11.8.0**.

Here's a screencap from our Crashlytics dashboard:
![screenshot from 2018-01-19 10-01-54](https://user-images.githubusercontent.com/5402301/35164604-dbf0ec6a-fcff-11e7-839d-7dc1cb1b442f.png)

Here's the stacktrace:
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.chess/com.google.android.gms.auth.api.signin.internal.SignInHubActivity}: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.google.android.gms.auth.api.signin.internal.SignInConfiguration
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2678)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2747)
       at android.app.ActivityThread.access$900(ActivityThread.java:187)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1585)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5879)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1119)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:885)
Caused by android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.google.android.gms.auth.api.signin.internal.SignInConfiguration
       at android.os.Parcel.readException(Parcel.java:1548)
       at android.os.Parcel.readException(Parcel.java:1499)
       at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2639)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1573)
       at android.app.Activity.startActivityForResult(Activity.java:3830)
       at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:67)
       at android.app.Activity.startActivityForResult(Activity.java:3787)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:720)
       at com.google.android.gms.auth.api.signin.internal.SignInHubActivity.onCreate(Unknown Source)
       at android.app.Activity.performCreate(Activity.java:6127)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1125)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2631)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2747)
       at android.app.ActivityThread.access$900(ActivityThread.java:187)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1585)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5879)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1119)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:885)
```

**Comment by mwgray** [comment]
Hi @autonomousapps,

Can you provide some more information?  When you say 9x, do you mean you only see it happen 9 times per day out of 300,000 users?

Also, what is the package name/link of your app?

**Comment by autonomousapps** [comment]
@mwgray thanks for the reply.
1. Yes, 9 times per day out of 300k daily average users (1.2M/month). Note huge, but I don't like adding new crashes to my app. And generally I care about anything that happens >1 time per day.
2. https://play.google.com/store/apps/details?id=com.chess&hl=en

I can provide any more info you need -- just ask :)

**Comment by isaisachen** [comment]
@autonomousapps, looks like it mostly happened to Meizu devices. I think these devices don't have Google Play services.

It's unfortunately that it's crashing, but just a note that Google Sign-In can't work on these devices any ways. A workaround is to skip sign-in when Google Play services is not available.

`GoogleApiAvailability googleAPI = GoogleApiAvailability.getInstance();
  if (!googleAPI.isGooglePlayServicesAvailable(this)) {
     // show message and skip sign-in.
  }`

**Comment by autonomousapps** [comment]
@isaisachen thanks for the hint! I'll take a look.

**Comment by autonomousapps** [comment]
For anyone else looking at this, the `isGooglePlayServicesAvailable(Context)` method doesn't return a `boolean`. It returns an `int` ([doc](https://developers.google.com/android/reference/com/google/android/gms/common/GoogleApiAvailability.html#isGooglePlayServicesAvailable(android.content.Context))). If you don't care about edge cases, you can check for availability by comparing to `ConnectionResult.SUCCESS`.

**Comment by isaisachen** [comment]
Thanks @autonomousapps I corrected my code snippet above.

**Comment by autonomousapps** [comment]
I'm going to roll this fix out to prod today. I should know by Monday if it addresses the crashes. I'll update this issue then!

**Comment by aritraroy** [comment]
@autonomousapps Any updates on this? We are also facing the same issue, but in our case, the users do have Google Play Services is installed on their device. The crash just happens once or twice when they try to login but works after that. It mainly happens on Xioami devices.

**Comment by autonomousapps** [comment]
@aritraroy I no longer see that crash, after first checking for the presence of GPS. If you're seeing that crash when you're sure GPS is available, it might be a different issue.

**Comment by aritraroy** [comment]
@autonomousapps Cool, btw which version of Play Services are you in?

**Comment by autonomousapps** [comment]
@aritraroy play services 11.8.0.

**Comment by akkishinde** [comment]
@aritraroy lets try this
